"""
Report Generator for Self-Learning System

Generates daily markdown reports summarizing findings,
papers, and optimization proposals.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from .analysis_engine import AnalysisResult
from .knowledge_base import DailyReport, KnowledgeBase

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates daily learning reports in markdown format."""

    def __init__(self, knowledge_base: KnowledgeBase, reports_dir: str | Path = "reports"):
        self._kb = knowledge_base
        self._reports_dir = Path(reports_dir)
        self._reports_dir.mkdir(parents=True, exist_ok=True)

    async def generate_daily_report(self, analysis: AnalysisResult) -> str:
        """Generate and save a daily report from analysis results."""
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

        # Build markdown report
        md = self._build_markdown(today, analysis)

        # Save report file
        report_path = self._reports_dir / f"{today}.md"
        report_path.write_text(md, encoding="utf-8")
        logger.info("Daily report saved to %s", report_path)

        # Save to knowledge base
        report = DailyReport(
            date=today,
            github_findings_count=len(analysis.high_relevance_findings),
            papers_count=len(analysis.high_relevance_papers),
            proposals_count=len(analysis.proposals),
            top_findings=[
                {"title": f.get("title", ""), "url": f.get("url", ""), "stars": f.get("stars", 0)}
                for f in analysis.high_relevance_findings[:5]
            ],
            top_papers=[
                {"title": p.get("title", ""), "url": p.get("url", ""), "citations": p.get("citation_count", 0)}
                for p in analysis.high_relevance_papers[:5]
            ],
            proposals=[
                {"title": p.title, "impact": p.estimated_impact, "modules": p.affected_modules}
                for p in analysis.proposals[:5]
            ],
            summary=analysis.summary,
        )
        await self._kb.save_daily_report(report)

        return str(report_path)

    def _build_markdown(self, date: str, analysis: AnalysisResult) -> str:
        """Build markdown content for the daily report."""
        lines = [
            f"# Self-Learning Report — {date}",
            f"",
            f"Generated by LMO Self-Learning System",
            f"",
            "---",
            f"",
            analysis.summary,
            f"",
            "---",
            f"",
            f"## GitHub Findings ({len(analysis.high_relevance_findings)} high-relevance)",
            f"",
        ]

        if analysis.high_relevance_findings:
            for i, f in enumerate(analysis.high_relevance_findings[:10], 1):
                lines.append(f"### {i}. [{f.get('title', 'N/A')}]({f.get('url', '#')})")
                lines.append(f"- **Stars**: {f.get('stars', 0)}")
                lines.append(f"- **Language**: {f.get('language', 'N/A')}")
                lines.append(f"- **Score**: {f.get('score', 0)}")
                desc = f.get("description", "")
                if desc:
                    lines.append(f"- **Description**: {desc[:200]}")
                lines.append("")
        else:
            lines.append("_No high-relevance GitHub findings this cycle._")
            lines.append("")

        lines.extend([
            "---",
            "",
            f"## Academic Papers ({len(analysis.high_relevance_papers)} high-relevance)",
            "",
        ])

        if analysis.high_relevance_papers:
            for i, p in enumerate(analysis.high_relevance_papers[:10], 1):
                lines.append(f"### {i}. [{p.get('title', 'N/A')}]({p.get('url', '#')})")
                lines.append(f"- **Authors**: {', '.join(p.get('authors', [])[:3])}")
                lines.append(f"- **Published**: {p.get('published_at', 'N/A')}")
                lines.append(f"- **Citations**: {p.get('citation_count', 0)}")
                lines.append(f"- **Source**: {p.get('source', 'N/A')}")
                abstract = p.get("abstract", "")
                if abstract:
                    lines.append(f"- **Abstract**: {abstract[:300]}...")
                lines.append("")
        else:
            lines.append("_No high-relevance papers this cycle._")
            lines.append("")

        lines.extend([
            "---",
            "",
            f"## Optimization Proposals ({len(analysis.proposals)})",
            "",
        ])

        if analysis.proposals:
            for i, p in enumerate(analysis.proposals[:10], 1):
                lines.append(f"### {i}. [{p.estimated_impact.upper()}] {p.title}")
                lines.append(f"- **Source**: {p.source_url}")
                lines.append(f"- **Modules**: {', '.join(p.affected_modules)}")
                lines.append(f"- **Test Plan**:")
                lines.append(p.test_plan)
                lines.append("")
        else:
            lines.append("_No new optimization proposals this cycle._")
            lines.append("")

        lines.extend([
            "---",
            "",
            "## Next Steps",
            "",
            "1. Review high-impact proposals and prioritize implementation",
            "2. Run benchmarks for validated proposals",
            "3. Integrate successful optimizations into the codebase",
            "",
        ])

        return "\n".join(lines)

    async def get_report_history(self, limit: int = 30) -> List[Dict[str, Any]]:
        """Get recent daily reports from the knowledge base."""
        # Use the latest report for now; a full history query could be added
        report = await self._kb.get_latest_report()
        return [report] if report else []
